# Generated by Django 4.1.5 on 2023-01-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BooksDB',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=200)),
                ('category', models.CharField(default='', max_length=50)),
                ('subcategory', models.CharField(default='', max_length=50)),
                ('publisher', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=5000)),
                ('price', models.IntegerField(default=0)),
                ('publish_date', models.DateField()),
                ('pages', models.IntegerField(default=0)),
                ('image', models.ImageField(default='', upload_to='bookReview/images')),
            ],
        ),
    ]
