# Generated by Django 4.1.5 on 2023-01-27 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookReview', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BooksDB',
            new_name='Book',
        ),
    ]
