# Generated by Django 4.1.5 on 2023-01-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookReview', '0002_rename_booksdb_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.IntegerField(default=0),
        ),
    ]
