# Generated by Django 4.1.5 on 2023-01-27 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookReview', '0003_alter_book_publish_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
    ]
