# Generated by Django 4.1.6 on 2023-02-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookReview', '0004_remove_book_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=700)),
            ],
        ),
    ]
