# Generated by Django 4.1.6 on 2023-02-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookReview', '0008_alter_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSignup',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(default='', max_length=254)),
            ],
        ),
    ]
