# Generated by Django 4.1.6 on 2023-03-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookReview', '0009_usersignup'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn_10',
            field=models.IntegerField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn_13',
            field=models.IntegerField(default=0, max_length=50),
        ),
    ]
