# Generated by Django 4.1.6 on 2023-03-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookReview', '0010_book_isbn_10_book_isbn_13'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn_10',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn_13',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
