# Generated by Django 4.1.6 on 2023-03-22 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookReview', '0011_alter_book_isbn_10_alter_book_isbn_13'),
    ]

    operations = [
        migrations.CreateModel(
            name='favouriteBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_from_database', models.BooleanField(verbose_name=True)),
                ('book_from_api', models.BooleanField(verbose_name=False)),
                ('book_id_api', models.CharField(max_length=30)),
                ('book_id_db', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookReview.book')),
                ('current_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
