# Generated by Django 4.1.6 on 2023-03-23 11:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookReview', '0013_alter_favouritebook_book_id_api'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favouritebook',
            unique_together={('current_user', 'book_id_db', 'book_id_api')},
        ),
    ]
