# Generated by Django 4.1.6 on 2023-03-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookReview', '0015_alter_favouritebook_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouritebook',
            name='book_from_api',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='favouritebook',
            name='book_from_database',
            field=models.BooleanField(),
        ),
    ]
