# Generated by Django 4.1.6 on 2023-03-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookReview', '0016_alter_favouritebook_book_from_api_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favouritebook',
            name='book_from_database',
        ),
        migrations.AlterField(
            model_name='favouritebook',
            name='book_from_api',
            field=models.BooleanField(default=False),
        ),
    ]
