# Generated by Django 4.1.6 on 2023-04-05 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookReview', '0018_userreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreview',
            name='date',
        ),
    ]
