# Generated by Django 4.1.6 on 2023-04-05 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookReview', '0019_remove_userreview_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreview',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
