# Generated by Django 4.1.6 on 2023-04-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookReview', '0020_userreview_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreview',
            name='id',
        ),
        migrations.AddField(
            model_name='userreview',
            name='reviewId',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
